package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysDictData;
import java.util.List;

public interface SysDictDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dictCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    int insert(SysDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    SysDictData selectByPrimaryKey(Integer dictCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    List<SysDictData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDictData record);
}