package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysJob;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("jobId") Integer jobId, @Param("jobName") String jobName, @Param("jobGroup") String jobGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insert(SysJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    SysJob selectByPrimaryKey(@Param("jobId") Integer jobId, @Param("jobName") String jobName, @Param("jobGroup") String jobGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    List<SysJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysJob record);
}