package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysLogininfor;
import java.util.List;

public interface SysLogininforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated
     */
    int insert(SysLogininfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated
     */
    SysLogininfor selectByPrimaryKey(Integer infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated
     */
    List<SysLogininfor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_logininfor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysLogininfor record);
}