package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysOperLog;
import java.util.List;

public interface SysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int insert(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    SysOperLog selectByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    List<SysOperLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOperLog record);
}