package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysPost;
import java.util.List;

public interface SysPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int insert(SysPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    SysPost selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    List<SysPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPost record);
}