package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysUserPost;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("postId") String postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    int insert(SysUserPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_post
     *
     * @mbg.generated
     */
    List<SysUserPost> selectAll();
}