package com.lizp.springboot.persist;

import com.lizp.springboot.domain.SysUserOnline;
import java.util.List;

public interface SysUserOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated
     */
    int insert(SysUserOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated
     */
    SysUserOnline selectByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated
     */
    List<SysUserOnline> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_online
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserOnline record);
}