package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.descpt
     *
     * @mbg.generated
     */
    private String descpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.insert_uid
     *
     * @mbg.generated
     */
    private Integer insertUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.descpt
     *
     * @return the value of role.descpt
     *
     * @mbg.generated
     */
    public String getDescpt() {
        return descpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.descpt
     *
     * @param descpt the value for role.descpt
     *
     * @mbg.generated
     */
    public void setDescpt(String descpt) {
        this.descpt = descpt == null ? null : descpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.code
     *
     * @return the value of role.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.code
     *
     * @param code the value for role.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.insert_uid
     *
     * @return the value of role.insert_uid
     *
     * @mbg.generated
     */
    public Integer getInsertUid() {
        return insertUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.insert_uid
     *
     * @param insertUid the value for role.insert_uid
     *
     * @mbg.generated
     */
    public void setInsertUid(Integer insertUid) {
        this.insertUid = insertUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.insert_time
     *
     * @return the value of role.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.insert_time
     *
     * @param insertTime the value for role.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.update_time
     *
     * @return the value of role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.update_time
     *
     * @param updateTime the value for role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", descpt=").append(descpt);
        sb.append(", code=").append(code);
        sb.append(", insertUid=").append(insertUid);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}