package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Id;

public class SysDept implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.dept_id
	 *
	 * @mbg.generated
	 */
	@Id
	private Integer deptId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.parent_id
	 *
	 * @mbg.generated
	 */
	private Integer parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.dept_name
	 *
	 * @mbg.generated
	 */
	private String deptName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.order_num
	 *
	 * @mbg.generated
	 */
	private Integer orderNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.leader
	 *
	 * @mbg.generated
	 */
	private String leader;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.phone
	 *
	 * @mbg.generated
	 */
	private String phone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.email
	 *
	 * @mbg.generated
	 */
	private String email;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.status
	 *
	 * @mbg.generated
	 */
	private Integer status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.create_by
	 *
	 * @mbg.generated
	 */
	private String createBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.update_by
	 *
	 * @mbg.generated
	 */
	private String updateBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_dept.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_dept
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.dept_id
	 *
	 * @return the value of sys_dept.dept_id
	 *
	 * @mbg.generated
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.dept_id
	 *
	 * @param deptId
	 *            the value for sys_dept.dept_id
	 *
	 * @mbg.generated
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.parent_id
	 *
	 * @return the value of sys_dept.parent_id
	 *
	 * @mbg.generated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.parent_id
	 *
	 * @param parentId
	 *            the value for sys_dept.parent_id
	 *
	 * @mbg.generated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.dept_name
	 *
	 * @return the value of sys_dept.dept_name
	 *
	 * @mbg.generated
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.dept_name
	 *
	 * @param deptName
	 *            the value for sys_dept.dept_name
	 *
	 * @mbg.generated
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.order_num
	 *
	 * @return the value of sys_dept.order_num
	 *
	 * @mbg.generated
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.order_num
	 *
	 * @param orderNum
	 *            the value for sys_dept.order_num
	 *
	 * @mbg.generated
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.leader
	 *
	 * @return the value of sys_dept.leader
	 *
	 * @mbg.generated
	 */
	public String getLeader() {
		return leader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.leader
	 *
	 * @param leader
	 *            the value for sys_dept.leader
	 *
	 * @mbg.generated
	 */
	public void setLeader(String leader) {
		this.leader = leader == null ? null : leader.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.phone
	 *
	 * @return the value of sys_dept.phone
	 *
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.phone
	 *
	 * @param phone
	 *            the value for sys_dept.phone
	 *
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.email
	 *
	 * @return the value of sys_dept.email
	 *
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.email
	 *
	 * @param email
	 *            the value for sys_dept.email
	 *
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.status
	 *
	 * @return the value of sys_dept.status
	 *
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.status
	 *
	 * @param status
	 *            the value for sys_dept.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.create_by
	 *
	 * @return the value of sys_dept.create_by
	 *
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.create_by
	 *
	 * @param createBy
	 *            the value for sys_dept.create_by
	 *
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.create_time
	 *
	 * @return the value of sys_dept.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.create_time
	 *
	 * @param createTime
	 *            the value for sys_dept.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.update_by
	 *
	 * @return the value of sys_dept.update_by
	 *
	 * @mbg.generated
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.update_by
	 *
	 * @param updateBy
	 *            the value for sys_dept.update_by
	 *
	 * @mbg.generated
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dept.update_time
	 *
	 * @return the value of sys_dept.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dept.update_time
	 *
	 * @param updateTime
	 *            the value for sys_dept.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_dept
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deptId=").append(deptId);
		sb.append(", parentId=").append(parentId);
		sb.append(", deptName=").append(deptName);
		sb.append(", orderNum=").append(orderNum);
		sb.append(", leader=").append(leader);
		sb.append(", phone=").append(phone);
		sb.append(", email=").append(email);
		sb.append(", status=").append(status);
		sb.append(", createBy=").append(createBy);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateBy=").append(updateBy);
		sb.append(", updateTime=").append(updateTime);
		sb.append("]");
		return sb.toString();
	}
}