package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;

public class SysJobLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    private Integer jobLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.method_name
     *
     * @mbg.generated
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.job_message
     *
     * @mbg.generated
     */
    private String jobMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.is_exception
     *
     * @mbg.generated
     */
    private Integer isException;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job_log.exception_info
     *
     * @mbg.generated
     */
    private String exceptionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_job_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_log_id
     *
     * @return the value of sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    public Integer getJobLogId() {
        return jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_log_id
     *
     * @param jobLogId the value for sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    public void setJobLogId(Integer jobLogId) {
        this.jobLogId = jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_name
     *
     * @return the value of sys_job_log.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_name
     *
     * @param jobName the value for sys_job_log.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_group
     *
     * @return the value of sys_job_log.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_group
     *
     * @param jobGroup the value for sys_job_log.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.method_name
     *
     * @return the value of sys_job_log.method_name
     *
     * @mbg.generated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.method_name
     *
     * @param methodName the value for sys_job_log.method_name
     *
     * @mbg.generated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.params
     *
     * @return the value of sys_job_log.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.params
     *
     * @param params the value for sys_job_log.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.job_message
     *
     * @return the value of sys_job_log.job_message
     *
     * @mbg.generated
     */
    public String getJobMessage() {
        return jobMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.job_message
     *
     * @param jobMessage the value for sys_job_log.job_message
     *
     * @mbg.generated
     */
    public void setJobMessage(String jobMessage) {
        this.jobMessage = jobMessage == null ? null : jobMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.is_exception
     *
     * @return the value of sys_job_log.is_exception
     *
     * @mbg.generated
     */
    public Integer getIsException() {
        return isException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.is_exception
     *
     * @param isException the value for sys_job_log.is_exception
     *
     * @mbg.generated
     */
    public void setIsException(Integer isException) {
        this.isException = isException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.create_time
     *
     * @return the value of sys_job_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.create_time
     *
     * @param createTime the value for sys_job_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job_log.exception_info
     *
     * @return the value of sys_job_log.exception_info
     *
     * @mbg.generated
     */
    public String getExceptionInfo() {
        return exceptionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job_log.exception_info
     *
     * @param exceptionInfo the value for sys_job_log.exception_info
     *
     * @mbg.generated
     */
    public void setExceptionInfo(String exceptionInfo) {
        this.exceptionInfo = exceptionInfo == null ? null : exceptionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobLogId=").append(jobLogId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", methodName=").append(methodName);
        sb.append(", params=").append(params);
        sb.append(", jobMessage=").append(jobMessage);
        sb.append(", isException=").append(isException);
        sb.append(", createTime=").append(createTime);
        sb.append(", exceptionInfo=").append(exceptionInfo);
        sb.append("]");
        return sb.toString();
    }
}