package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class SysMenu implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_id
	 *
	 * @mbg.generated
	 */
	private Integer menuId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_name
	 *
	 * @mbg.generated
	 */
	private String menuName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.parent_id
	 *
	 * @mbg.generated
	 */
	private Integer parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.order_num
	 *
	 * @mbg.generated
	 */
	private Integer orderNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.url
	 *
	 * @mbg.generated
	 */
	private String url;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.menu_type
	 *
	 * @mbg.generated
	 */
	private String menuType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.visible
	 *
	 * @mbg.generated
	 */
	private Integer visible;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.perms
	 *
	 * @mbg.generated
	 */
	private String perms;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.icon
	 *
	 * @mbg.generated
	 */
	private String icon;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.create_by
	 *
	 * @mbg.generated
	 */
	private String createBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.create_time
	 *
	 * @mbg.generated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.update_by
	 *
	 * @mbg.generated
	 */
	private String updateBy;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.update_time
	 *
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_menu.remark
	 *
	 * @mbg.generated
	 */
	private String remark;
	private List<SysMenu> children;

	public List<SysMenu> getChildren() {
		return children;
	}

	public void setChildren(List<SysMenu> children) {
		this.children = children;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_menu
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_id
	 *
	 * @return the value of sys_menu.menu_id
	 *
	 * @mbg.generated
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_id
	 *
	 * @param menuId
	 *            the value for sys_menu.menu_id
	 *
	 * @mbg.generated
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_name
	 *
	 * @return the value of sys_menu.menu_name
	 *
	 * @mbg.generated
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_name
	 *
	 * @param menuName
	 *            the value for sys_menu.menu_name
	 *
	 * @mbg.generated
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName == null ? null : menuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.parent_id
	 *
	 * @return the value of sys_menu.parent_id
	 *
	 * @mbg.generated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.parent_id
	 *
	 * @param parentId
	 *            the value for sys_menu.parent_id
	 *
	 * @mbg.generated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.order_num
	 *
	 * @return the value of sys_menu.order_num
	 *
	 * @mbg.generated
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.order_num
	 *
	 * @param orderNum
	 *            the value for sys_menu.order_num
	 *
	 * @mbg.generated
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.url
	 *
	 * @return the value of sys_menu.url
	 *
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.url
	 *
	 * @param url
	 *            the value for sys_menu.url
	 *
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.menu_type
	 *
	 * @return the value of sys_menu.menu_type
	 *
	 * @mbg.generated
	 */
	public String getMenuType() {
		return menuType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.menu_type
	 *
	 * @param menuType
	 *            the value for sys_menu.menu_type
	 *
	 * @mbg.generated
	 */
	public void setMenuType(String menuType) {
		this.menuType = menuType == null ? null : menuType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.visible
	 *
	 * @return the value of sys_menu.visible
	 *
	 * @mbg.generated
	 */
	public Integer getVisible() {
		return visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.visible
	 *
	 * @param visible
	 *            the value for sys_menu.visible
	 *
	 * @mbg.generated
	 */
	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.perms
	 *
	 * @return the value of sys_menu.perms
	 *
	 * @mbg.generated
	 */
	public String getPerms() {
		return perms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.perms
	 *
	 * @param perms
	 *            the value for sys_menu.perms
	 *
	 * @mbg.generated
	 */
	public void setPerms(String perms) {
		this.perms = perms == null ? null : perms.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.icon
	 *
	 * @return the value of sys_menu.icon
	 *
	 * @mbg.generated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.icon
	 *
	 * @param icon
	 *            the value for sys_menu.icon
	 *
	 * @mbg.generated
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.create_by
	 *
	 * @return the value of sys_menu.create_by
	 *
	 * @mbg.generated
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.create_by
	 *
	 * @param createBy
	 *            the value for sys_menu.create_by
	 *
	 * @mbg.generated
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy == null ? null : createBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.create_time
	 *
	 * @return the value of sys_menu.create_time
	 *
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.create_time
	 *
	 * @param createTime
	 *            the value for sys_menu.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.update_by
	 *
	 * @return the value of sys_menu.update_by
	 *
	 * @mbg.generated
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.update_by
	 *
	 * @param updateBy
	 *            the value for sys_menu.update_by
	 *
	 * @mbg.generated
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy == null ? null : updateBy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.update_time
	 *
	 * @return the value of sys_menu.update_time
	 *
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.update_time
	 *
	 * @param updateTime
	 *            the value for sys_menu.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.remark
	 *
	 * @return the value of sys_menu.remark
	 *
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.remark
	 *
	 * @param remark
	 *            the value for sys_menu.remark
	 *
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_menu
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", menuId=").append(menuId);
		sb.append(", menuName=").append(menuName);
		sb.append(", parentId=").append(parentId);
		sb.append(", orderNum=").append(orderNum);
		sb.append(", url=").append(url);
		sb.append(", menuType=").append(menuType);
		sb.append(", visible=").append(visible);
		sb.append(", perms=").append(perms);
		sb.append(", icon=").append(icon);
		sb.append(", createBy=").append(createBy);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateBy=").append(updateBy);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", remark=").append(remark);
		sb.append("]");
		return sb.toString();
	}
}