package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;

public class SysOperLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.oper_id
     *
     * @mbg.generated
     */
    private Integer operId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.oper_url
     *
     * @mbg.generated
     */
    private String operUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.oper_ip
     *
     * @mbg.generated
     */
    private String operIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.oper_param
     *
     * @mbg.generated
     */
    private String operParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.error_msg
     *
     * @mbg.generated
     */
    private String errorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_oper_log.oper_time
     *
     * @mbg.generated
     */
    private Date operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.oper_id
     *
     * @return the value of sys_oper_log.oper_id
     *
     * @mbg.generated
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.oper_id
     *
     * @param operId the value for sys_oper_log.oper_id
     *
     * @mbg.generated
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.title
     *
     * @return the value of sys_oper_log.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.title
     *
     * @param title the value for sys_oper_log.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.action
     *
     * @return the value of sys_oper_log.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.action
     *
     * @param action the value for sys_oper_log.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.method
     *
     * @return the value of sys_oper_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.method
     *
     * @param method the value for sys_oper_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.channel
     *
     * @return the value of sys_oper_log.channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.channel
     *
     * @param channel the value for sys_oper_log.channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.login_name
     *
     * @return the value of sys_oper_log.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.login_name
     *
     * @param loginName the value for sys_oper_log.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.dept_name
     *
     * @return the value of sys_oper_log.dept_name
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.dept_name
     *
     * @param deptName the value for sys_oper_log.dept_name
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.oper_url
     *
     * @return the value of sys_oper_log.oper_url
     *
     * @mbg.generated
     */
    public String getOperUrl() {
        return operUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.oper_url
     *
     * @param operUrl the value for sys_oper_log.oper_url
     *
     * @mbg.generated
     */
    public void setOperUrl(String operUrl) {
        this.operUrl = operUrl == null ? null : operUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.oper_ip
     *
     * @return the value of sys_oper_log.oper_ip
     *
     * @mbg.generated
     */
    public String getOperIp() {
        return operIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.oper_ip
     *
     * @param operIp the value for sys_oper_log.oper_ip
     *
     * @mbg.generated
     */
    public void setOperIp(String operIp) {
        this.operIp = operIp == null ? null : operIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.oper_param
     *
     * @return the value of sys_oper_log.oper_param
     *
     * @mbg.generated
     */
    public String getOperParam() {
        return operParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.oper_param
     *
     * @param operParam the value for sys_oper_log.oper_param
     *
     * @mbg.generated
     */
    public void setOperParam(String operParam) {
        this.operParam = operParam == null ? null : operParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.status
     *
     * @return the value of sys_oper_log.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.status
     *
     * @param status the value for sys_oper_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.error_msg
     *
     * @return the value of sys_oper_log.error_msg
     *
     * @mbg.generated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.error_msg
     *
     * @param errorMsg the value for sys_oper_log.error_msg
     *
     * @mbg.generated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_oper_log.oper_time
     *
     * @return the value of sys_oper_log.oper_time
     *
     * @mbg.generated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_oper_log.oper_time
     *
     * @param operTime the value for sys_oper_log.oper_time
     *
     * @mbg.generated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operId=").append(operId);
        sb.append(", title=").append(title);
        sb.append(", action=").append(action);
        sb.append(", method=").append(method);
        sb.append(", channel=").append(channel);
        sb.append(", loginName=").append(loginName);
        sb.append(", deptName=").append(deptName);
        sb.append(", operUrl=").append(operUrl);
        sb.append(", operIp=").append(operIp);
        sb.append(", operParam=").append(operParam);
        sb.append(", status=").append(status);
        sb.append(", errorMsg=").append(errorMsg);
        sb.append(", operTime=").append(operTime);
        sb.append("]");
        return sb.toString();
    }
}