package com.lizp.springboot.domain;

import java.io.Serializable;
import java.util.Date;

public class SysUserOnline implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.sessionId
	 *
	 * @mbg.generated
	 */
	private String sessionid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.login_name
	 *
	 * @mbg.generated
	 */
	private String loginName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.dept_name
	 *
	 * @mbg.generated
	 */
	private String deptName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.ipaddr
	 *
	 * @mbg.generated
	 */
	private String ipaddr;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.browser
	 *
	 * @mbg.generated
	 */
	private String browser;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.os
	 *
	 * @mbg.generated
	 */
	private String os;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.status
	 *
	 * @mbg.generated
	 */
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.start_timestsamp
	 *
	 * @mbg.generated
	 */
	private Date startTimestsamp;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.last_access_time
	 *
	 * @mbg.generated
	 */
	private Date lastAccessTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user_online.expire_time
	 *
	 * @mbg.generated
	 */
	private Integer expireTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sys_user_online
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;
	private OnlineSession session;

	public OnlineSession getSession() {
		return session;
	}

	public void setSession(OnlineSession session) {
		this.session = session;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.sessionId
	 *
	 * @return the value of sys_user_online.sessionId
	 *
	 * @mbg.generated
	 */
	public String getSessionid() {
		return sessionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.sessionId
	 *
	 * @param sessionid
	 *            the value for sys_user_online.sessionId
	 *
	 * @mbg.generated
	 */
	public void setSessionid(String sessionid) {
		this.sessionid = sessionid == null ? null : sessionid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.login_name
	 *
	 * @return the value of sys_user_online.login_name
	 *
	 * @mbg.generated
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.login_name
	 *
	 * @param loginName
	 *            the value for sys_user_online.login_name
	 *
	 * @mbg.generated
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.dept_name
	 *
	 * @return the value of sys_user_online.dept_name
	 *
	 * @mbg.generated
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.dept_name
	 *
	 * @param deptName
	 *            the value for sys_user_online.dept_name
	 *
	 * @mbg.generated
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName == null ? null : deptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.ipaddr
	 *
	 * @return the value of sys_user_online.ipaddr
	 *
	 * @mbg.generated
	 */
	public String getIpaddr() {
		return ipaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.ipaddr
	 *
	 * @param ipaddr
	 *            the value for sys_user_online.ipaddr
	 *
	 * @mbg.generated
	 */
	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr == null ? null : ipaddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.browser
	 *
	 * @return the value of sys_user_online.browser
	 *
	 * @mbg.generated
	 */
	public String getBrowser() {
		return browser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.browser
	 *
	 * @param browser
	 *            the value for sys_user_online.browser
	 *
	 * @mbg.generated
	 */
	public void setBrowser(String browser) {
		this.browser = browser == null ? null : browser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.os
	 *
	 * @return the value of sys_user_online.os
	 *
	 * @mbg.generated
	 */
	public String getOs() {
		return os;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.os
	 *
	 * @param os
	 *            the value for sys_user_online.os
	 *
	 * @mbg.generated
	 */
	public void setOs(String os) {
		this.os = os == null ? null : os.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.status
	 *
	 * @return the value of sys_user_online.status
	 *
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.status
	 *
	 * @param status
	 *            the value for sys_user_online.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.start_timestsamp
	 *
	 * @return the value of sys_user_online.start_timestsamp
	 *
	 * @mbg.generated
	 */
	public Date getStartTimestsamp() {
		return startTimestsamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.start_timestsamp
	 *
	 * @param startTimestsamp
	 *            the value for sys_user_online.start_timestsamp
	 *
	 * @mbg.generated
	 */
	public void setStartTimestsamp(Date startTimestsamp) {
		this.startTimestsamp = startTimestsamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.last_access_time
	 *
	 * @return the value of sys_user_online.last_access_time
	 *
	 * @mbg.generated
	 */
	public Date getLastAccessTime() {
		return lastAccessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.last_access_time
	 *
	 * @param lastAccessTime
	 *            the value for sys_user_online.last_access_time
	 *
	 * @mbg.generated
	 */
	public void setLastAccessTime(Date lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user_online.expire_time
	 *
	 * @return the value of sys_user_online.expire_time
	 *
	 * @mbg.generated
	 */
	public Integer getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user_online.expire_time
	 *
	 * @param expireTime
	 *            the value for sys_user_online.expire_time
	 *
	 * @mbg.generated
	 */
	public void setExpireTime(Integer expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_user_online
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", sessionid=").append(sessionid);
		sb.append(", loginName=").append(loginName);
		sb.append(", deptName=").append(deptName);
		sb.append(", ipaddr=").append(ipaddr);
		sb.append(", browser=").append(browser);
		sb.append(", os=").append(os);
		sb.append(", status=").append(status);
		sb.append(", startTimestsamp=").append(startTimestsamp);
		sb.append(", lastAccessTime=").append(lastAccessTime);
		sb.append(", expireTime=").append(expireTime);
		sb.append("]");
		return sb.toString();
	}
}